### REGISTER USR
POST http://localhost:3000/api/auth/registerUser HTTP/1.1
Content-Type: application/json

{
	"username": "maha1",
	"email": "rawan@mu1nia.maha",
	"password": "ppppppppp1#"
}

### LOGIN USER
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
	"email": "maha@munia.su3maya2",
	"password": "ppppppppp1#P",
	"add": "hey"
}

### LOGOUT USER
POST http://localhost:3000/api/auth/logout HTTP/1.1
Content-Type: application/json

{}
