### REGISTER USR
POST http://localhost:3000/api/auth/registerUser HTTP/1.1
Content-Type: application/json

{
	"username": "dina",
	"email": "dina@gmail.com",
	"password": "ppppppppp1#P"
}

### LOGIN USER
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
	"email": "maha@gmail.com",
	"password": "ppppppppp1#P"
}

### LOGOUT USER
POST http://localhost:3000/api/auth/logout HTTP/1.1
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzU2Mjg2ODk4LCJleHAiOjE3NTYyOTA0OTh9.iZ41eNdxOtzpAP4iaAOJeHkX2NByqJGWEQKe_i2zvhQ

{}