### QUERY USER'S FRIENDS
GET http://localhost:3000/api/friends HTTP/1.1
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzU2Mjg3ODkwLCJleHAiOjE3NTYyOTE0OTB9.qbrhyTeeeZDgNRGv1dD5mEOob8q_lTagHArB_0lcCIQ

{}

### SEND REQUEST
POST http://localhost:3000/api/friends/sendRequest HTTP/1.1
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzU2Mjg3ODkwLCJleHAiOjE3NTYyOTE0OTB9.qbrhyTeeeZDgNRGv1dD5mEOob8q_lTagHArB_0lcCIQ


{
	"userId": 2
}

### ACCEPT REQUEST
POST http://localhost:3000/api/friends/acceptRequest HTTP/1.1
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzU2Mjg3ODkwLCJleHAiOjE3NTYyOTE0OTB9.qbrhyTeeeZDgNRGv1dD5mEOob8q_lTagHArB_0lcCIQ


{
	"userId": 3
}

### DECLINE REQUEST
POST http://localhost:3000/api/friends/declineRequest HTTP/1.1
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzU2Mjg3ODkwLCJleHAiOjE3NTYyOTE0OTB9.qbrhyTeeeZDgNRGv1dD5mEOob8q_lTagHArB_0lcCIQ


{
	"userId": 2
}

### REMOVE FRIEND
POST http://localhost:3000/api/friends/removeFriend HTTP/1.1
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzU2Mjg3ODkwLCJleHAiOjE3NTYyOTE0OTB9.qbrhyTeeeZDgNRGv1dD5mEOob8q_lTagHArB_0lcCIQ


{
	"userId": 2
}

### BLOCK FRIEND
POST http://localhost:3000/api/friends/blockFriend HTTP/1.1
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzU2Mjg3ODkwLCJleHAiOjE3NTYyOTE0OTB9.qbrhyTeeeZDgNRGv1dD5mEOob8q_lTagHArB_0lcCIQ


{
	"userId": 2
}

### SEARCH USERS
GET  http://localhost:3000/api/friends/searchUser?q=s&page=1 HTTP/1.1
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzU2Mjg3ODkwLCJleHAiOjE3NTYyOTE0OTB9.qbrhyTeeeZDgNRGv1dD5mEOob8q_lTagHArB_0lcCIQ


{}
